
# This workflow builds FastJ Game Library on the latest version of Mac OS using Gradle.

name: Build-MacOS

on: [push, pull_request]

jobs:
  build-macos:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          architecture: x64
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build using Gradle
        run: ./gradlew build --info
